#include "irods_ms_plugin.hpp"
#include "objInfo.h"
#include "reDataObjOpr.hpp"
#include "collCreate.h"
#include "dataObjPut.h"
#include "collection.hpp"
#include "rcMisc.h"

// This file is generated by go compiler, based on name of .go file in current directory
#include "msiextract_image_metadata.h"

extern "C"
irods::ms_table_entry* plugin_factory() {

    // Specify number of arguments (excluding last *ruleExecInfo_t)
    int numArgs = 2;

    irods::ms_table_entry* msvc = new irods::ms_table_entry(numArgs);
    msvc->add_operation(

        // Make sure this matches the .cpp filename (excluding the lib prefix) in the current directory.
        "msiextract_image_metadata",
        std::function<int(
            msParam_t*,
            msParam_t*,
            ruleExecInfo_t*)>(ExtractImageMetadata));
    
    return msvc;
}
